### ISSUE TITLE
Create an overview of features of existing prototype

### ISSUE THREAD

**Issue by k00ni** [AKSW/building-navigator#1]
Make a simple feature list (separate them by type: UI, browser, ...).

**Comment by k00ni** [comment]
http://pcai042.informatik.uni-leipzig.de/~spe16/

**Comment by simeonackermann** [comment]
# Functional

- locate current position (automatically or manually)
- search location with auto-complete
- show locations on the map
- filter locations
	- accessibility (complete/partly suitable for wheelchairs or just available) of toilets, elevators, entrance and parkings
	- if special help for hearing or visually handicapped is available
	- by category (education, traffic, restaurant, health, ...)
- click on a location on the map opens a pop up with name, address and short information
- button to show further information (category, elevator, access, parking, toilets ... and may notes) of a location
- button to show a location from the list of locations on the map
- accessibility settings (increase/decrease font and button size)
- close pop up with (x), buttons to hide sidebar/filter
- distance from current location
- functions of *OpenStreetMap*
	- zoom in shows more details
	- zoom in/out via scroll or +/- keys
	- move map via drag/drop or arrow keys
	- ...

# UI

- search-bar with submit button and accessibility settings button on top
- left sidebar with the list of locations and more information
- bottom filter bar
- buttons to hide/close elements
- map in the center of the view with UI from *OpenStreetMap*
- blue marker for locations on the map
- black marker for current location
- red marker for selected location
- zoom in/out buttons on right side with icons
- locate current location on right side with icon
- scale of current zoom (100 m - 30000 km) on bottom right side

# Misc

- help/manual, with definition of common pictograms and usage of the filters
- currently maximum 25 (?) locations are shown on the map

**Comment by simeonackermann** [comment]
I think we can close this issue.
