### ISSUE TITLE
build basic interface and test it with a screenreader

### ISSUE THREAD

**Issue by k00ni** [AKSW/building-navigator#10]

**Comment by k00ni** [comment]
* [ ] remove "Karte" from main menu
* [ ] show "Ergebnisse auf Karten anzeigen" link in the result list
* [ ] show "Gebäude auf Karte anzeigen" link for each result entry
* [ ] remove material UI and bootstrap UI example
* [ ] instead of key-value-view in result list, use "Lift ist vorhanden" or "Lift ist nicht vorhanden"
  * [ ] show entries as a simple comma separated list
* [ ] add category-select box to filter box (to select only restaurants, ...)

**Comment by simeonackermann** [comment]
fixed in current commit. 

But still needs some screendreader tests.
