### ISSUE TITLE
use Virtuoso as databackend through rdfstore-js

### ISSUE THREAD

**Issue by simeonackermann** [AKSW/building-navigator#15]

**Comment by simeonackermann** [comment]
@k00ni rdfstore-js acts as a standalone store. Its not possible to use it with Virtuoso as backend.
But its not a big thing to do ajax requests to the virtuoso sparql endpoint and still have rdfstore-js as alternative local store.

**Comment by k00ni** [comment]
@simeonackermann i think you can use the rdfstore-js to query any RDF source: files or SPARQL endpoints. Its not a store itself i think. As i remember it, @GeorgesAlkhouri once told me, that you can pass it a SPARQL endpoint and it will handle all the communication with it.

**Comment by simeonackermann** [comment]
I dont see any documented way to do this. It's only possible to load resources from remote uri. And cubevizjs uses either local rdfstore or remote store via Ajax requests. 

Am 23. November 2016 14:24:46 MEZ, schrieb Konrad Abicht <notifications@github.com>:
>@simeonackermann i think you can use the rdfstore-js to query any RDF
>source: files or SPARQL endpoints. Its not a store itself i think. As i
>remember it, @GeorgesAlkhouri once told me, that you can pass it a
>SPARQL endpoint and it will handle all the communication with it.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/AKSW/building-navigator/issues/15#issuecomment-262511563

-- 
Diese Nachricht wurde von meinem CyanogenMod Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by GeorgesAlkhouri** [comment]
@simeonackermann is right, cubeviz handles the queries to the store. Thats what I meant when I said that 

> you can pass it a
SPARQL endpoint and it will handle all the communication

I meant cubeviz, not rdfstore-js

**Comment by k00ni** [comment]
Ok @GeorgesAlkhouri and @simeonackermann, please correct me, if i am wrong: my understanding of the rdfstore-js is, that you give him some SPARQL and it will fire it on a SPARQL endpoint. Furthermore, it will return the result back to you. So you dont have to care about any endpoint in particular, you just focusing on writing your SPARQL and compute returned results.

If you need to deal with Virtuoso by yourself, why bother using rdfstore-js after all?

**Comment by simeonackermann** [comment]
Rdfstore-js is a javascript implementation of an rdf-store with sparql endpoint. For cubevizjs its used to load uploaded data or a file into a local rdf store. I just used it because we didn't wanted an extra virtuoso server and its good and easy to use.

**Comment by simeonackermann** [comment]
But for our case: having a big dataset and don't need any write or change actions a remote server like Virtuoso is of cause the better solution.

**Comment by simeonackermann** [comment]
Done with b50ced97e6933ca816617f5e37e3b48f86558473

Requests are made as asynchronous ajax requests with https://github.com/github/fetch, but are specified to Virtuoso 7.x by now.
