### ISSUE TITLE
Please update README.md

### ISSUE THREAD

**Issue by k00ni** [AKSW/building-navigator#17]
Because of the latest changes, please adapt our README:

* [ ] add end user section
  * [ ] add a screenshot of the software (somewhere on the top of the file)
* [x] add developer section
  * [x] adapt requirements to run the software
  * [x] link to used NPM docker container (new: https://github.com/k00ni/Docker-Nodejs-environment)

**Comment by k00ni** [comment]
Can you please check above what you already solved?

**Comment by simeonackermann** [comment]
What means "port documentation" ?

**Comment by simeonackermann** [comment]
Fixed with 859dc796bd60561301b49c7d6d5662c9e5630019

**Comment by k00ni** [comment]
Looks very good!
