### ISSUE TITLE
Using just the dist-folder isn't working (BuildingNavigator is not defined)

### ISSUE THREAD

**Issue by k00ni** [AKSW/building-navigator#19]
I copied the dist folder to my webhosting and wanted to use the index.html. But after calling it in the browser i ran into the following exceptions:

```
Uncaught Invariant Violation: Minified React error #37; 
visit http://facebook.github.io/react/docs/error-decoder.html?invariant=37 
for the full message or use the non-minified dev environment for full 
errors and additional helpful warnings.

Uncaught ReferenceError: BuildingNavigator is not defined
```

Generated main.min.js does **NOT** contain BuildingNavigator. Any idea?

![screenshot from 2017-01-10 15 48 24](https://cloud.githubusercontent.com/assets/381727/21810511/6946b610-d74c-11e6-88ac-c8f9bcfb5ede.png)

**Comment by simeonackermann** [comment]
Should solved with latest commit 17e6db35d075ec5938368184a07ac1c5eefa519f  (it was an old main.min.js)

**Comment by k00ni** [comment]
Do you update `dist/main.min.js` on file changes or do i have to do that manually?

**Comment by simeonackermann** [comment]
I have do do it manually.

Am 10.01.2017 um 16:44 schrieb Konrad Abicht:

**Comment by k00ni** [comment]
Are there many steps? Can we move that into a Makefile or something to reduce the time load?

**Comment by simeonackermann** [comment]
It's just one webpack call with some parameters. To simplify we can put them into the npm packages file and call it e.g. `npm build` 
But I don't think it's a good idea the recreate the dist with each new commit 

Am 16. Januar 2017 11:05:10 MEZ schrieb Konrad Abicht <notifications@github.com>:
>Are there many steps? Can we move that into a Makefile or something to
>reduce the time load?
>
>-- 
>You are receiving this because you were assigned.
>Reply to this email directly or view it on GitHub:
>https://github.com/AKSW/building-navigator/issues/19#issuecomment-272819962

-- 
Diese Nachricht wurde von meinem CyanogenMod Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by k00ni** [comment]
> But I don't think it's a good idea the recreate the dist with each new commit

Why not? The dist folder should be valid and contain the latest changes. If we want to carry out packages, which update only after days/weeks/months ... we could use Github's release section. But i wanted to use the dist from the beginning, to be able to try out the app without any further work.

Could you sketch here how it should work to update dist-folder manually, by calling like `make update-dist`. On each Git commit sounds hard to implement.

**Comment by simeonackermann** [comment]
https://github.com/AKSW/building-navigator/commit/177bf27902bcf514ed7b570cf1f75fa14a73b6ec implements command `npm build-dist`. It has to executed in the running Docker container.

**Comment by k00ni** [comment]
Thanks! Will look into it.

**Comment by k00ni** [comment]
**package.json:**
```
"devDependencies": {
        ...
        "write-file-webpack-plugin": "*"
    }
```

**webpack.config.json:**
```
...
var WriteFilePlugin = require('write-file-webpack-plugin');

module.exports = {
    ...
    output: {
        ...
    },
    plugins: [
        new WriteFilePlugin() // plugin to write compiled JS into dist folder
    ],
    ...
}
```

**Comment by simeonackermann** [comment]
As I pointed out the disadvantages of using WriteFilePlugin (esp. js min size) we may close this issue?

To build dist on each commit/push we can create a pre-push hook as a reminder or programmatically create dist and append to commit.

**Comment by k00ni** [comment]
As we decided we use two configurations, dev and prod, for future releases.
