### ISSUE TITLE
Rework the logging system

### ISSUE THREAD

**Issue by k00ni** [AKSW/building-navigator#20]
Code currently contains a lot of 

```
console.log('FOUND');
```
or
```
console.log('layerEls:', layerEls);
```
which may be helpful during development, but later on, we pollute not only console but don't track or evaluate these information. I would suggest deploying a basic logging system.

**Comment by simeonackermann** [comment]
Done in branch [rebuild](https://github.com/AKSW/building-navigator/tree/rebuild) with [Logger](https://github.com/AKSW/building-navigator/blob/rebuild/src/utils/Logger.js). Console outputs should only printed if mode is not `production`
