### ISSUE TITLE
Complete UI

### ISSUE THREAD

**Issue by simeonackermann** [AKSW/building-navigator#27]
## UI
- [x] toggle Sidebar button
- [x] results detailed view (notes, opening-times, ...)
- [x] mobile view (full sidebar)
- [x] checkbox for filters general help, help for blind/hearing
- [x] refactor a11y Class
- [x] a11y icons in marker popup
- [x] several margins/pagings, font-sizes etc.
- [x] break too long titles in result list
- [x] fix popup width on small devices -> OR directly open sidebar with building-details if clicked marker
- [x] add loader icon for submit button (after search), and on loading building details
- [x] highlight current (selected on map) result entry

## Functional
- [x] click on "Show details" in map popup behavior
- [x] click "Show on map", pan/zoom to building, show current marker
- [ ] ~~order buildings by distance to center for map -> to discuss!~~
- [x] order buildings by a11y for results list
- [x] update visible buildings after zoom/pan map
- [x] selected marker on map
- [x] group marker-popup on map for buildings on same location
- [x] show next x buildings (paging results)

## Accessibility
- [x] aria label for screen readers, try with chomevox
- [x] autofocus behavior / tab-focus

**Comment by k00ni** [comment]
Are these the "only" TODOs to catch up with the latest version 2?

**Comment by simeonackermann** [comment]
Maybe there are some more small points which i dont see at the moment, but generally yes, i think so.
