### ISSUE TITLE
Make a short analysis of mapybezbarier.cz

### ISSUE THREAD

**Issue by k00ni** [AKSW/building-navigator#3]
Link: [https://mapybezbarier.cz/en](https://mapybezbarier.cz/en)

Make a short analysis of it and see, which features we also should implement.

Before that, finish #1 please.

**Comment by simeonackermann** [comment]
First a short analysis:

# Functional

- map with functions of *OpenStreetMap*/*GoogleMaps* like zoom and move
- search with autocomplete
- filter locations
	- by data source (professional or community)
	- by level of accessibility (complete, partly, not), more described in the help
	- by type of place (cultural, church, historical, education, ...) (with counter)
- different type of map: "A Map", Satellite, *GoogleMaps*
- set current location
- select a location on the map opens a pop up with short information
	- name, address, website and icons for accessibility of toilet, changing table and entrances
	- button to show detailed information
		- name, address, website, data source
		- toilet, elevator, entrance, surface etc. with additional information (dimensions, limitations or difficulty), parking situation
		- description of the place, entrance, toilets
- combine to many locations in higher levels of zoom to one marker
- combined marker for locations on the same place

# UI

- header with logo, navigation, and language selector (cz/eng)
- sidebar with several filters
- map in the center
- search field in the upper left of the map
- buttons on bottom left for help, code and download
- markers for locations with colors (green: accessible, orange: partly accessible, red: inaccessible) and mostly with icons for the category of the location
- blue marker for combined locations with counter
- colorful icons for locations on the same place with counter
- pop up of a location with short information and icons 
- right sidebar with detailed information of a selected location
- buttons to hide/close sidebars or pop ups
- footer bar about the project and partners

**Comment by simeonackermann** [comment]
# Features to adopt

## Functional

- workflow: don't force the user to set a location, just show the map and locations
- showing all locations (not just 30)
- combine too many locations to one marker (if in too high zoom mode)
- live filtering of locations

## UI

- cleaner (modern) layout, better fonts
- filter in sidebar
- detailed information in other sidebar
- category-icon in marker
- pictograms/icons in pop-ups and detail view

**Comment by simeonackermann** [comment]
Issue can be closed.
