### ISSUE TITLE
Tiles provider

### ISSUE THREAD

**Issue by simeonackermann** [AKSW/building-navigator#33]
Latest build https://github.com/AKSW/building-navigator/commit/035dc490ba885b8b6b96e221942b58834bd5d1bc updates the tiles provider to OpenStreetmap DE style. I hope it looks more common.

Other tiles are available here:
https://leaflet-extras.github.io/leaflet-providers/preview/
https://switch2osm.org/providers/

Or nonfree: Here, Skobbler, MapQuest (Humanitarian style, requires leaflet plugin/SDK)

**Comment by k00ni** [comment]
Current demo looks good, so closed for now.
