### ISSUE TITLE
Reactivate search

### ISSUE THREAD

**Issue by simeonackermann** [AKSW/building-navigator#35]
How to find a specific building without the search?

**Comment by k00ni** [comment]
At this point, no one really ask for this feature. So if there is still no one, even after quesioning the BVL, we shouldn't bother to implement it.

**Comment by simeonackermann** [comment]
I think the searchfield is very usefull if you search for a specific building, which could be, as I think, a common usecase.

The implementation is already done. It's currently just uncommented.

**Comment by simeonackermann** [comment]
Fixed with 076817a
