### ISSUE TITLE
Discuss: Preload building data in background

### ISSUE THREAD

**Issue by simeonackermann** [AKSW/building-navigator#37]

**Comment by k00ni** [comment]
Did you experience major performance issues? Or are there stutters in the browser? If nothing of this, why preloading?

**Comment by simeonackermann** [comment]
On my smartphone it takes about 3 to 6 seconds from clicking a marker to the detailed results view. May we can improve it through preloading the details of the visible buildings.

**Comment by k00ni** [comment]
Think about storing data using https://github.com/samyk/evercookie

**Comment by k00ni** [comment]
Looks for prefetching concepts and approaches. Try to preload building information when user on welcome screen. Load further information, when user moves the map or something.

**Comment by simeonackermann** [comment]
Evercookies main point is to use all available browsers store (cookie, flash, html5 store, ...) and tries to avoids that users delete its content, which couldn't be our target.

**Comment by simeonackermann** [comment]
After some thinking I decided to don't use preloading of data, because of to less positive effects to the end user. It does not really improve the speed of the app.

**Comment by k00ni** [comment]
> Evercookies main point is to use all available browsers store (cookie, flash, html5 store, ...) and tries to avoids that users delete its content, which couldn't be our target.

Why is that a problem here? We only store building information to speed up loading for users, nothing personal or sensitive.

**Comment by simeonackermann** [comment]
First it has some [caveats](https://github.com/samyk/evercookie#caveats)
Secondly i think its too intrusive: 
> If cookie data is removed from any of the storage mechanisms, evercookie aggressively re-creates it in each mechanism as long as one is still intact

**Comment by k00ni** [comment]
Good points. I agree to leave that for now.
