### ISSUE TITLE
Implement rdfstore-js as data handler

### ISSUE THREAD

**Issue by k00ni** [AKSW/building-navigator#4]
Currently the prototype directly imports a CSV file and uses it as "database". Change this by enabling [rdfstore-js](https://github.com/antoniogarrote/rdfstore-js) to be used as RDF store.

**Comment by k00ni** [comment]
Please check if this issue bothers you: https://github.com/antoniogarrote/rdfstore-js/issues/128

**Comment by simeonackermann** [comment]
First tries seems successful. I can read an load the le-places RDF file into the rdfstore.

**Comment by k00ni** [comment]
Could you test major browser like Firefox, Chromium and Edge?

**Comment by simeonackermann** [comment]
Successfully tested with FF 49 and Chrome 55.

**Comment by k00ni** [comment]
Good, i guess the issue is gone, at least for now and we continue to use this as our major data backend.
