### ISSUE TITLE
Vectorized BVL icons

### ISSUE THREAD

**Issue by k00ni** [AKSW/building-navigator#40]
From the question mark to http://www.le-online.de/9999.gif

**Comment by simeonackermann** [comment]
Do you know if the BVL has vectorized pictograms?

**Comment by k00ni** [comment]
Yes, but they are not ready yet. Can we delay this a bit?

**Comment by simeonackermann** [comment]
Sure.

**Comment by k00ni** [comment]
We use icons from the following source: https://teilhabeplan.behindertenverband-leipzig.de/piktogramme.php

Icons added and production instance updated.

**Comment by simeonackermann** [comment]
Why did you use a light parking icon instead the dark blue one like all others? 

![Icons](https://screenshotscdn.firefoxusercontent.com/images/121cdbc3-6c5f-462b-959e-bd110e4b4330.png)

I think this is a bit confusing and at  [behindertenverband-leipzig](https://teilhabeplan.behindertenverband-leipzig.de/piktogramme.php) I only find the dark one...

**Comment by k00ni** [comment]
Good point. Will change it.

**Comment by k00ni** [comment]
Done.
