### ISSUE TITLE
Create Docker based development environment

### ISSUE THREAD

**Issue by k00ni** [AKSW/building-navigator#42]
* [x] Node Docker (Node, NPM, Webpack, Babel for ECMA6)
* [x] Virtuoso Docker

**Repo:** https://github.com/AKSW/building-navigator-docker

**Comment by simeonackermann** [comment]
Closed with https://github.com/AKSW/building-navigator-docker/commit/eb33604e02f759574acbe0b9e7ca2c62747d14df
