### ISSUE TITLE
Perfomance issues on change route. Is this a development-only issue?

### ISSUE THREAD

**Issue by simeonackermann** [AKSW/building-navigator#46]

**Comment by k00ni** [comment]
What exactly is the problem here?

**Comment by simeonackermann** [comment]
The loading time on change a route (eg going to results and back to search) increases on changing the route several times.

Problem also exists on productive.

**Comment by k00ni** [comment]
Do you know the cause? And if so, how hard is it to fix?

**Comment by simeonackermann** [comment]
Problem already exists on last release /master).

Even going back to search, which is not any hard calculation, causes higher loading time.

**Comment by simeonackermann** [comment]
I dont know yet. 

Even CPU load increases.

**Comment by simeonackermann** [comment]
I will do some research later...

**Comment by k00ni** [comment]
Did you test only locally or did you checked https://behindertenverband-leipzig.de/gebaeude-navigator/#/search too?

**Comment by simeonackermann** [comment]
I get this issue locally and online

**Comment by simeonackermann** [comment]
Ok, I guess I found the problem. Its because a background cloning of all current states (buildings, filters etc) on change a route, what is required to set the state on using browser back functionality. 
I will see if it can work somehow else.

**Comment by simeonackermann** [comment]
Fixed with 89e40e4
