### ISSUE TITLE
RDFStore-JS Demo

### ISSUE THREAD

**Issue by simeonackermann** [AKSW/building-navigator#48]
For demo purposes: as long as no productive server (with triple store) is available, use a small RDF data set and load in from an in memory JS store.

**Comment by simeonackermann** [comment]
See  888898c

**Comment by simeonackermann** [comment]
Filesize of `main.min.js` is 9,5 MB, because it has to include all buildings data

**Comment by simeonackermann** [comment]
Works with firefox, but for me not with Chrome (loading of building details failed)

**Comment by k00ni** [comment]
Did you include all RDF or just a chunk? If its just the file size, i am fine with way less, say 10 buildings. Could this change get Chrome to work?

**Comment by simeonackermann** [comment]
I shrinked the demo to 100 buildings, which is actually enough to get some more results and still has an acceptable file size (2,2MB)
For any reason it does NOT run in Chrome on local execution. BUT running it online works good, eg. see here: http://asimeon.de/building-navigator

The build is available on branch [round-4-rdfstore](https://github.com/AKSW/building-navigator/tree/round-4-rdfstorejs/dist)

**Comment by k00ni** [comment]
Nice! Lets talk about this tomorrow.
