### ISSUE TITLE
Navigation component

### ISSUE THREAD

**Issue by simeonackermann** [AKSW/building-navigator#54]
To implement the routing component, a routing service is required.

Available routing services are:

- http://project-osrm.org/ with https://wiki.openstreetmap.org/wiki/Nominatim
- https://www.graphhopper.com/
- https://www.mapbox.com/

Questions: 
- License, Terms of Servoce OK?
- Limitations on requests per minute/day

**Comment by k00ni** [comment]
First a short feedback for each system.

### mapbox
- limitations for free account seems more than enough for now (according to https://www.mapbox.com/pricing/)
- i didn't found any license information, but we are non-commercial and therefore the free plan should fit

### graphhopper
- it provides less requests per day as mapbox (https://www.graphhopper.com/pricing/)
- **found no license information**, but on the pricing site, they said "*The Free-package is allowed for non-commercial usage only, has a limited credit count per minute and a limited set of vehicle profiles.*"

### Project OSRM + Nominatim
- i have found no real information about the system; i assume we have to host that by ourselves, which is currently not possible.

I prefer mapbox, because they allow the most requests per day. But i am trust you, if you think another system fits better. Whats important for me is, that we have no fees, only services (not self-hosted) and if the routing-system stops working (e.g. if limitations reached), our app must keep working.

**Comment by simeonackermann** [comment]
Mapbox has its terms of services here: https://www.mapbox.com/tos/#geocoding and it  says:

> You may only use responses from the Geocoding API ("Geocodes") in conjunction with a Mapbox map.

That means we cannot use it, as we are using openstreetmap. The curious thing I wondered about is why the leaflet-routing plugin implements it.

OSRM should has its limitations here: https://github.com/Project-OSRM/osrm-backend/wiki/Api-usage-policy, but this page has only content in the history: https://github.com/Project-OSRM/osrm-backend/wiki/Api-usage-policy/_compare/5e5903fd7eb36fa8c56a178695edc7c030a7bf75

Its similar like Nomination: https://operations.osmfoundation.org/policies/nominatim/, which mainly brings 1 request per seconds as limitation.

**Comment by k00ni** [comment]
OK, and what will you do now?

**Comment by simeonackermann** [comment]
After playing around with OSRM/Nomination I already had issues with `Too many requests` (it seems a bit buggy, because I also get them after a longer time of waiting).

As an alternative, we could implement the mapbox routing. Its allowed if we even use the mapbox tiles (the images of the map), that is very easy to implement (just changing an url). BUT the style looks different than currently. A list of styles is available here: https://www.mapbox.com/maps/ . For us the [mapbox streets](https://www.mapbox.com/maps/streets/) might be the best. Its also possible to change all element styles on the map, but I think the default should be ok for the moment.

What do you say, staying purely OSM without navigation or using Mapbox with navigtion?

**Comment by k00ni** [comment]
Ok, so do you mean OSRM/Nomination is still valid?

> Its allowed if we even use the mapbox tiles (the images of the map), that is very easy to implement (just changing an url).

Did they replace our OSM tiles/images? Can you paste me an image, how it would looks like in the end?

I currently don't understand what each solution can bring to the table, also can't follow you on all the problems you mentioned. Whats important for me is: 
* we need a long term solution, which is not that big of a deal to maintain
* it has to have no restricting license (we need the freedom to change or use, what we want; also, we can't compromise the BVL or Leipzig city in anyway)
* we can mix up different solutions, like OSM + Mapbox (if i understand that correctly), when the visual style keep consistent

I would suggest you try out the solution you prefer in a separate branch. If you got to a certain point, please send me some screenshots displaying the new solution. That would be great.

**Comment by simeonackermann** [comment]
Visually the only thing which would change with mapbox is the style of the map like the following:

![bildschirmfoto vom 2018-05-30 10-25-49](https://user-images.githubusercontent.com/6428217/40708660-50bcdb48-63f4-11e8-84ad-f9e470da2487.png)

Compared to the current:

[
![bildschirmfoto vom 2018-05-30 10-24-41](https://user-images.githubusercontent.com/6428217/40708639-444150ec-63f4-11e8-8f39-8dd6886320a3.png)
](url)

Butt there are a lot more styles possible

**Comment by simeonackermann** [comment]
- with mapbox we dont have more to maintain than currently
- the user requests are limited to 50.000 per month https://www.mapbox.com/pricing/

**Comment by simeonackermann** [comment]
Stores, public buildings, restaurants etc are still available. In the end its the OSM data with another style

**Comment by k00ni** [comment]
> Stores, public buildings, restaurants etc are still available. In the end its the OSM data with another style

Great! Mapbox data even looks a little bit cleaner. Would you mind adding a few words to our documentation (e.g. Mapbox) about how we use it? Do you we have to expand our license information for Mapbox?

**Comment by simeonackermann** [comment]
> Great! Mapbox data even looks a little bit cleaner

Even my view.

As attribution we only have to add Mapbox beside the OpenStreetmap link on the right bottom on the map.

**Comment by simeonackermann** [comment]
Allright.
The navigation component is implemented on branch [round-4-navigation](https://github.com/AKSW/building-navigator/tree/round-4-navigation) and even with rdfstorejs on [round-4-rdfstorejs-navigation](https://github.com/AKSW/building-navigator/tree/round-4-rdfstorejs-navigation) (handy for demonstration purposes).

The implemention details are listed in commit 2fdba262491c2961f959fa425543d4edf752b858

You can see a working demo at http://asimeon.de/building-navigator/

**Comment by k00ni** [comment]
I will send the demo to the BVL and Co. so that can get an impression of the new feature. Thank you!

**Comment by k00ni** [comment]
Is there a login to see how many requests were made in a months? Is this thing working via API key?

**Comment by simeonackermann** [comment]
Yes, but its currently my account. I will create I account for the Building Navigator...

**Comment by k00ni** [comment]
Do you use an API key? If so, how can we manage, that nobody else uses our key? That is especially important if you think deployment or versioning control.

**Comment by simeonackermann** [comment]
I created a new mapbox account for the building-navigator. After login at https://www.mapbox.com/signin/ you can see the stats of map/navigatio requests.
I will send you the login data via mail.

**Comment by simeonackermann** [comment]
To use mapbox the usage of an API key is required and there is currently no way to totally hide it.
The only way to do this would be a proxy server.

Some other solutions, like rotating the key after some time, are listed at https://www.mapbox.com/signin/

**Comment by k00ni** [comment]
Can you send me the access credentials to Mapbox please?

This issue seems done, isn't it?

**Comment by simeonackermann** [comment]
Further navigation TODO #57
